# Generated by Django 5.2 on 2025-05-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_location_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='address',
            new_name='landmark',
        ),
    ]
