# Generated by Django 5.2 on 2025-06-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_contactmessage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
    ]
