# Generated by Django 5.2 on 2025-06-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_location_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.PositiveIntegerField(blank=True, max_length=6),
        ),
    ]
